import React, { useEffect } from "react";
import Navbar from "../Components/Navbar";
import Footer from "../Components/Footer";
import GoToTop from "../Components/Top";
// import Banner_1 from "../assets/mediaBanner.png";
import grayBg from "../assets/grayBg.png";
import { useNavigate } from "react-router-dom";

// import img1 from "../assets/news/1.png";
// import img2 from "../assets/news/2.png";
// import img3 from "../assets/news/3.png";
import { TagTwoTone } from "@mui/icons-material";

const TermAndCondition = () => {
  const navigate = useNavigate();
  useEffect(() => {
    document.title = "News - Eupheus";
  }, []);
  return (
    <div
      className="bg-[#dbdbdb] overflow-hidden"
      style={{ backgroundImage: `url(${grayBg})` }}
    >
      <Navbar highlight={"media"} />

      {/* <div className="sm:h-[100vh] relative w-[100vw]">
        <img
          className="sm:h-[100vh] h-auto sm:mt-0 mt-[9rem] object-cover w-[100vw]"
          src={Banner_1}
          alt=""
        />
      </div> */}

      <div className="w-full flex justify-center items-center lg:mt-[8rem] 2xl:mt-[10rem] md:mt-[7rem] sm:mt-[11rem] mt-[11rem]">
        <h1 className="text-[2rem] underline sm:text-[3rem] text-red-700 font-bold">
          TERMS & CONDITIONS
        </h1>
      </div>

      <div className="flex flex-col my-8  sm:px-[3rem] px-[1.5rem] gap-4">
        <span>
          <span className="text-xl font-semibold">
            LAST REVISION: [06-08-2021]
          </span>{" "}
          <br />
          <span className="text-sm">
            This Terms of Service Agreement is an electronic record in terms of
            Information Technology Act, 2000 ("Act") and rules thereunder as
            applicable and the amended provisions pertaining to electronic
            records in various statutes as amended by the Information Technology
            (Amendment) Act, 2019. This agreement is generated by a computer
            system and does not require any physical or digital signatures.
          </span>
          <br />
          <span className="text-sm">
            This agreement is published in accordance with the provisions of
            Rule 4 (1) of the Information Technology (Reasonable Security
            Practices and Procedures and Sensitive Personal Data or Information)
            Rules, 2011 that require publishing the rules and regulations,
            privacy policy and terms and conditions for access and/or usage of
            https://eupheus.co.in ("Website").
          </span>
          <br />
          <span className="text-sm">
            In these terms and conditions of use ("Terms of Use"), the following
            terms shall have the meaning as ascribed to them below:
          </span>
          <br />
          <span className="text-sm">
            <span className="font-bold">"User"</span> refers to you, the person
            visiting, accessing and/or using the Website by means of any
            communication device.
          </span>
          <br />
          <span className="text-sm">
            <span className="font-bold">"Proficiency Learning Solutions"</span>{" "}
            refers to Proficiency Learning Solutions Private Limited, a company
            incorporated under the relevant provisions of the Companies Act,
            2013, having Corporate Identity No. U80904DL2016PTC309293 and having
            its registered office address at 99, DSIDC, SHED, O.I.A. PHASE NO.1,
            OKHLA NEW DELHI – 110020, India, which is the owner of all rights in
            this Website.
          </span>
          <br />
          <span className="text-sm">
            All references to <span className="font-bold">"You"</span> and{" "}
            <span className="font-bold">"Your"</span> shall mean the User. All
            references to{" "}
            <span className="font-bold">
              "Proficiency Learning Solutions", “Eupheus Learning” "Company",
              "We", "Us"
            </span>{" "}
            and <span className="font-bold">"Our"</span> shall mean Proficiency
            Learning Solutions Pvt. Ltd.
          </span>
          <br />
          <span className="text-sm">
            This is a legal and binding agreement between you i.e. the User of
            the Website and the Company and states the terms that govern your
            use of the Website. By accessing this Website, you consent, agree
            and undertake to abide, be bound by and adhere to the Terms of Use.
          </span>
          <br />
          <span className="text-sm">
            PLEASE READ THIS TERMS OF SERVICE AGREEMENT CAREFULLY. BY USING THIS
            WEBSITE OR ORDERING PRODUCTS FROM THIS WEBSITE YOU AGREE TO BE BOUND
            BY ALL OF THE TERMS AND CONDITIONS OF THIS AGREEMENT. <br />
            This Terms of Service Agreement (the "Agreement") governs your use
            of this website, https://eupheus.co.in (the "Website"), Proficiency
            Learning Solutions Pvt. Ltd. including its brand name Eupheus
            Learning ("Business Name") offer of products for purchase on this
            Website, or your purchase of products available on this Website.
            This Agreement includes, and incorporates by this reference, the
            policies and guidelines referenced below. The Company reserves the
            right to change or revise the terms and conditions of this Agreement
            at any time by posting any changes or a revised Agreement on this
            Website. The Company will alert you that changes or revisions have
            been made by indicating on the top of this Agreement the date it was
            last revised. The changed or revised Agreement will be effective
            immediately after it is posted on this Website. Your use of the
            Website following the posting any such changes or of a revised
            Agreement will constitute your acceptance of any such changes or
            revisions. Proficiency Learning Solutions encourages you to review
            this Agreement whenever you visit the Website to make sure that you
            understand the terms and conditions governing use of the Website.
            This Agreement does not alter in any way the terms or conditions of
            any other written agreement you may have with the Company for other
            products or services. If you do not agree to this Agreement
            (including any referenced policies or guidelines), please
            immediately terminate your use of the Website. If you would like to
            print this Agreement, please click the print button on your browser
            toolbar.
          </span>
        </span>
        <span>
          <span className="text-xl font-semibold underline">PRODUCTS</span>{" "}
          <br />
          <span className="text-sm">
            Terms of Offer. This Website offers for sale certain products (the
            "Products"). By placing an order for Products through this Website,
            you agree to the terms set forth in this Agreement.
            <br />
            <span className="font-bold">Customer Solicitation:</span> Unless you
            notify us, of your desire to opt out from further direct company
            communications and solicitations, you are agreeing to continue to
            receive further emails and/or call solicitations from us and our
            designated in house or third party call team(s), if any.
            <br />
            <span className="font-bold">Opt Out Procedure: </span>
            We provide 3 easy ways to opt out of from future solicitations. 1.
            You may use the opt out link found in any email solicitation that
            you may receive. 2. You may also choose to opt out, via sending your
            email address to: info@eupheus.in.
            <br />
            You may send a written remove request to Proficiency Learning
            Solutions Pvt. Ltd., A-12, Second Floor, Mohan Cooperative
            Industrial Estate, Main Mathura Road, Near Sarita Vihar Metro
            Station, New Delhi – 110044.
            <br />
            Proprietary Rights. The Company has proprietary rights and trade
            secrets in the Products. You may not copy, reproduce, resell or
            redistribute any Product manufactured and/or distributed by
            Proficiency Learning Solutions and/or Eupheus Learning. Proficiency
            Learning Solutions also has rights to all trademarks and trade dress
            and specific layouts of this webpage, including calls to action,
            text placement, images and other information.
            <br />
            Goods and Service Tax (GST). If you purchase any Products, you will
            be responsible for paying any applicable GST.
          </span>
        </span>
        <span>
          <span className="text-xl font-semibold underline">WEBSITE</span>{" "}
          <br />
          <span className="text-sm">
            Content; Intellectual Property; Third Party Links. In addition to
            making Products available, this Website also offers information and
            marketing materials. This Website also offers information, both
            directly and through indirect links to third-party websites, about
            nutritional and dietary supplements. To the extent that the Company
            does create the content on this Website, such content is protected
            by intellectual property laws of the India, foreign nations, and
            international bodies. Unauthorized use of the material may violate
            copyright, trademark, and/or other laws. You acknowledge that your
            use of the content on this Website is for personal, non-commercial
            use. Any links to third-party websites are provided solely as a
            convenience to you. The Company does not endorse the contents on any
            such third-party websites. The Company is not responsible for the
            content of or any damage that may result from your access to or
            reliance on these third-party websites. If you link to third-party
            websites, you do so at your own risk.
            <br />
            Use of Website; the Company is not responsible for any damages
            resulting from use of this website by anyone. You will not use the
            Website for illegal purposes. You will (1) abide by all applicable
            local, state, national, and international laws and regulations in
            your use of the Website (including laws regarding intellectual
            property), (2) not interfere with or disrupt the use and enjoyment
            of the Website by other users, (3) not resell material on the
            Website, (4) not engage, directly or indirectly, in transmission of
            "spam", chain letters, junk mail or any other type of unsolicited
            communication, and (5) not defame, harass, abuse, or disrupt other
            users of the Website
            <br />
            License. By using this Website, you are granted a limited,
            non-exclusive, non-transferable right to use the content and
            materials on the Website in connection with your normal,
            non-commercial, use of the Website. You may not copy, reproduce,
            transmit, distribute, or create derivative works of such content or
            information without prior express written authorization from the
            Company or the applicable third party (if third party content is at
            issue).
            <br />
            Posting. By posting, storing, or transmitting any content on the
            Website, you hereby grant the Company a perpetual, worldwide,
            non-exclusive, royalty-free, assignable, right and license to use,
            copy, display, perform, create derivative works from, distribute,
            have distributed, transmit and assign such content in any form, in
            all media now known or hereinafter created, anywhere in the world.
          </span>
        </span>
        <span>
          <span className="text-xl font-semibold underline">
            DISCLAIMER OF WARRANTIES
          </span>{" "}
          <br />
          <span className="text-sm">
            YOUR USE OF THIS WEBSITE AND/OR PRODUCTS ARE AT YOUR SOLE RISK. THE
            WEBSITE AND PRODUCTS ARE OFFERED ON AN "AS IS" AND "AS AVAILABLE"
            BASIS. THE COMPANY EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND,
            WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED
            WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
            NON-INFRINGEMENT WITH RESPECT TO THE PRODUCTS OR WEBSITE CONTENT, OR
            ANY RELIANCE UPON OR USE OF THE WEBSITE CONTENT OR PRODUCTS.
            ("PRODUCTS" INCLUDE TRIAL PRODUCTS.) WITHOUT LIMITING THE GENERALITY
            OF THE FOREGOING, THE COMPANY MAKES NO WARRANTY:
            <br /> <br />
            <TagTwoTone />
            &nbsp; THAT THE INFORMATION PROVIDED ON THIS WEBSITE IS ACCURATE,
            RELIABLE, COMPLETE, OR TIMELY.
            <br />
            <TagTwoTone />
            &nbsp; THAT THE LINKS TO THIRD-PARTY WEBSITES ARE TO INFORMATION
            THAT IS ACCURATE, RELIABLE, COMPLETE, OR TIMELY.
            <br />
            <TagTwoTone />
            &nbsp; NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED
            BY YOU FROM THIS WEBSITE WILL CREATE ANY WARRANTY NOT EXPRESSLY
            STATED HEREIN.
            <br />
            <TagTwoTone />
            &nbsp; AS TO THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE
            PRODUCTS OR THAT DEFECTS IN PRODUCTS WILL BE CORRECTED. REGARDING
            ANY PRODUCTS PURCHASED OR OBTAINED THROUGH THE WEBSITE.
            <br />
            <TagTwoTone />
            &nbsp; SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN
            WARRANTIES, SO SOME OF THE ABOVE EXCLUSIONS MAY NOT APPLY TO YOU.
          </span>
        </span>
        <span>
          <span className="text-xl font-semibold underline">
            LIMITATION OF LIABILITY
          </span>{" "}
          <br />
          <span className="text-sm">
            THE COMPANY’S ENTIRE LIABILITY, AND YOUR EXCLUSIVE REMEDY, IN LAW,
            IN EQUITY, OR OTHWERWISE, WITH RESPECT TO THE WEBSITE CONTENT AND
            PRODUCTS AND/OR FOR ANY BREACH OF THIS AGREEMENT IS SOLELY LIMITED
            TO THE AMOUNT YOU PAID, LESS SHIPPING AND HANDLING, FOR PRODUCTS
            PURCHASED VIA THE WEBSITE. <br /> THE COMPANY WILL NOT BE LIABLE FOR
            ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES
            IN CONNECTION WITH THIS AGREEMENT OR THE PRODUCTS IN ANY MANNER,
            INCLUDING LIABILITIES RESULTING FROM (1) THE USE OR THE INABILITY TO
            USE THE WEBSITE CONTENT OR PRODUCTS; (2) THE COST OF PROCURING
            SUBSTITUTE PRODUCTS OR CONTENT; (3) ANY PRODUCTS PURCHASED OR
            OBTAINED OR TRANSACTIONS ENTERED INTO THROUGH THE WEBSITE; OR (4)
            ANY LOST PROFITS YOU ALLEGE. <br /> SOME JURISDICTIONS DO NOT ALLOW
            THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR
            CONSEQUENTIAL DAMAGES SO SOME OF THE ABOVE LIMITATIONS MAY NOT APPLY
            TO YOU.
          </span>
        </span>
        <span>
          <span className="text-xl font-semibold underline">
            INDEMNIFICATION
          </span>{" "}
          <br />
          <span className="text-sm">
            You will release, indemnify, defend and hold harmless the Company
            and its subsidiaries, and any of its contractors, agents, employees,
            officers, directors, shareholders, affiliates and assigns from all
            liabilities, claims, damages, costs and expenses, including
            reasonable attorneys' fees and expenses, of third parties relating
            to or arising out of (1) this Agreement or the breach of your
            warranties, representations and obligations under this Agreement;
            (2) the Website content or your use of the Website content; (3) the
            Products or your use of the Products (including Trial Products); (4)
            any intellectual property or other proprietary right of any person
            or entity; (5) your violation of any provision of this Agreement; or
            (6) any information or data you supplied to the Company. When the
            Company is threatened with suit or sued by a third party, the
            Company may seek written assurances from you concerning your promise
            to indemnify the Company; your failure to provide such assurances
            may be considered by the Company to be a material breach of this
            Agreement. The Company will have the right to participate in any
            defense by you of a third-party claim related to your use of any of
            the Website content or Products, with counsel of the Company’s
            choice at its expense. The Company will reasonably cooperate in any
            defense by you of a third-party claim at your request and expense.
            You will have sole responsibility to defend the Company against any
            claim, but you must receive the Company prior written consent
            regarding any related settlement. The terms of this provision will
            survive any termination or cancellation of this Agreement or your
            use of the Website or Products.
          </span>
        </span>
        <span>
          <span className="text-xl font-semibold underline">PRIVACY</span>{" "}
          <br />
          <span className="text-sm">
            The Company believes strongly in protecting user privacy and
            providing you with notice of Eupheus Learning's use of data. Please
            refer to Proficiency Learning Privacy Policy, incorporated by
            reference herein, that is posted on the Website.
          </span>
        </span>

        <span>
          <span className="text-xl font-semibold underline">
            AGREEMENT TO BE BOUND
          </span>{" "}
          <br />
          <span className="text-sm">
            By using this Website or ordering Products, you acknowledge that you
            have read and agree to be bound by this Agreement and all terms and
            conditions on this Website.
          </span>
        </span>
        <span>
          <span className="text-xl font-semibold underline">GENERAL</span>{" "}
          <br />
          <span className="text-sm">
            Force Majeure. the Company will not be deemed in default hereunder
            or held responsible for any cessation, interruption or delay in the
            performance of its obligations hereunder due to earthquake, flood,
            fire, storm, natural disaster, act of God, spread of any epidemic,
            pandemic, viruses or fungus, war, terrorism, armed conflict, labor
            strike, lockout, or boycott or lockdowns imposed by Central or State
            Government(s) or any other Government Authority. <br />
            Cessation of Operation. the Company may at any time, in its sole
            discretion and without advance notice to you, cease operation of the
            Website and distribution of the Products. <br />
            Entire Agreement. This Agreement comprises the entire agreement
            between you and the Company and supersedes any prior agreements
            pertaining to the subject matter contained herein. <br />
            Effect of Waiver. The failure of the Company to exercise or enforce
            any right or provision of this Agreement will not constitute a
            waiver of such right or provision. If any provision of this
            Agreement is found by a court of competent jurisdiction to be
            invalid, the parties nevertheless agree that the court should
            endeavor to give effect to the parties' intentions as reflected in
            the provision, and the other provisions of this Agreement remain in
            full force and effect. <br />
            Governing Law; Jurisdiction. This Website originates from New Delhi.
            This Agreement will be governed by the laws of India without regard
            to its conflict of law principles to the contrary. Neither you nor
            the Company will commence or prosecute any suit, proceeding or claim
            to enforce the provisions of this Agreement, to recover damages for
            breach of or default of this Agreement, or otherwise arising under
            or by reason of this Agreement, other than in courts located in
            State of Delhi. By using this Website or ordering Products, you
            consent to the jurisdiction and venue of such courts in connection
            with any action, suit, proceeding or claim arising under or by
            reason of this Agreement. You hereby waive any right to trial by
            jury arising out of this Agreement and any related documents. <br />
            Statute of Limitation. You agree that regardless of any statute or
            law to the contrary, any claim or cause of action arising out of or
            related to use of the Website or Products or this Agreement must be
            filed within one (1) year after such claim or cause of action arose
            or be forever barred. <br />
            Waiver of Class Action Rights. BY ENTERING INTO THIS AGREEMENT, YOU
            HEREBY IRREVOCABLY WAIVE ANY RIGHT YOU MAY HAVE TO JOIN CLAIMS WITH
            THOSE OF OTHER IN THE FORM OF A CLASS ACTION OR SIMILAR PROCEDURAL
            DEVICE. ANY CLAIMS ARISING OUT OF, RELATING TO, OR CONNECTION WITH
            THIS AGREEMENT MUST BE ASSERTED INDIVIDUALLY. <br />
            Termination. The Company reserves the right to terminate your access
            to the Website if it reasonably believes, in its sole discretion,
            that you have breached any of the terms and conditions of this
            Agreement. Following termination, you will not be permitted to use
            the Website and the Company may, in its sole discretion and without
            advance notice to you, cancel any outstanding orders for Products.
            If your access to the Website is terminated, the Company reserves
            the right to exercise whatever means it deems necessary to prevent
            unauthorized access of the Website. This Agreement will survive
            indefinitely unless and until the Company chooses, in its sole
            discretion and without advance to you, to terminate it. <br />
            Domestic Use. The Company makes no representation that the Website
            or Products are appropriate or available for use in locations
            outside India. Users who access the Website from outside India do so
            at their own risk and initiative and must bear all responsibility
            for compliance with any applicable local laws. <br />
            <br />
            Assignment. You may not assign your rights and obligations under
            this Agreement to anyone. The Company may assign its rights and
            obligations under this Agreement in its sole discretion and without
            advance notice to you. <br />
            BY USING THIS WEBSITE OR ORDERING PRODUCTS FROM THIS WEBSITE YOU
            AGREE TO BE BOUND BY ALL OF THE TERMS AND CONDITIONS OF THIS
            AGREEMENT.
          </span>
        </span>
      </div>

      <Footer />
      <GoToTop />
    </div>
  );
};

export default TermAndCondition;
